[build-system]
requires = ["setuptools ~= 58.0", "cython ~= 0.29.0"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "2.0.2"
requests = "2.26.0"
beautifulsoup4 = "4.10.0"
transformers = "4.14.0"
tokenizers = { version = "0.10.3", build = "pyproject.toml" }
